In [16]:
import torch
from torch import nn
import torchvision
from PIL import Image

train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, transform=torchvision.transforms.ToTensor(), download=True)
test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True)

In [11]:
batch_size = 32
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=batch_size, num_workers=2)

for batch, labels in train_loader:
    print(batch)
    print(batch.shape)
    print(labels.shape)
    break

tensor([[[[0.0431, 0.0588, 0.1098,  ..., 0.3137, 0.3020, 0.2941],
          [0.0471, 0.0471, 0.0667,  ..., 0.3255, 0.3216, 0.3098],
          [0.0118, 0.0157, 0.0235,  ..., 0.2510, 0.3137, 0.3098],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0824, 0.0941, 0.1765,  ..., 0.5961, 0.5882, 0.5804],
          [0.0745, 0.0706, 0.0784,  ..., 0.5882, 0.5804, 0.5725],
          [0.0118, 0.0118, 0.0196,  ..., 0.4275, 0.5412, 0.5373],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.1098, 0.1176, 0.2196,  ..., 0.7647, 0.7529, 0.7451],
          [0.0941, 0.0863, 0.0863,  ..., 0.7294, 0.7294, 0.7216],
          [0.0118, 0.0196, 0.0275,  ..., 0

In [41]:
image = torch.randn(2, 3, 4, 4)

unfold = nn.Unfold(kernel_size=2, stride=2)
patches = unfold(image)
print(patches)
print(patches.shape)
patches.permute(0, 2, 1)


tensor([[[ 1.2831, -0.3208, -2.0809,  1.6519],
         [-1.0256, -0.1378, -0.1329,  0.6620],
         [-0.2154, -0.0494, -1.4097, -1.9643],
         [-2.5162, -0.1416, -1.4641, -0.4022],
         [-0.9363,  0.9479,  0.5668, -1.9584],
         [-0.5405, -1.0989,  0.7532, -0.1958],
         [-1.5478,  1.5591, -1.4531, -0.4249],
         [ 0.4122, -0.0878, -0.7576, -1.4417],
         [-0.0309, -3.0397,  0.4320, -0.2226],
         [-0.8247, -0.6984, -1.3548,  2.2460],
         [-1.0957, -0.3563,  0.7717,  1.0354],
         [-1.3537, -1.6059, -0.3452,  0.9453]],

        [[-0.4725,  0.7085,  0.5683,  0.3397],
         [-1.2263, -0.4835, -0.6713,  0.5344],
         [ 1.4721, -1.0864, -0.4869,  1.6715],
         [ 0.3415,  0.8348,  1.0110,  1.4443],
         [ 0.7669, -0.3810, -1.7588,  1.1891],
         [ 1.3516,  0.2156, -1.0722,  0.1882],
         [-0.4737, -0.7697, -0.2249, -1.1443],
         [ 0.2041,  2.0835, -0.5102, -0.7956],
         [-0.8163,  1.4204, -1.1861, -1.1962],
         [-

tensor([[[ 1.2831, -1.0256, -0.2154, -2.5162, -0.9363, -0.5405, -1.5478,
           0.4122, -0.0309, -0.8247, -1.0957, -1.3537],
         [-0.3208, -0.1378, -0.0494, -0.1416,  0.9479, -1.0989,  1.5591,
          -0.0878, -3.0397, -0.6984, -0.3563, -1.6059],
         [-2.0809, -0.1329, -1.4097, -1.4641,  0.5668,  0.7532, -1.4531,
          -0.7576,  0.4320, -1.3548,  0.7717, -0.3452],
         [ 1.6519,  0.6620, -1.9643, -0.4022, -1.9584, -0.1958, -0.4249,
          -1.4417, -0.2226,  2.2460,  1.0354,  0.9453]],

        [[-0.4725, -1.2263,  1.4721,  0.3415,  0.7669,  1.3516, -0.4737,
           0.2041, -0.8163, -1.7542, -0.0195, -0.0446],
         [ 0.7085, -0.4835, -1.0864,  0.8348, -0.3810,  0.2156, -0.7697,
           2.0835,  1.4204,  1.5933,  0.9316,  0.1635],
         [ 0.5683, -0.6713, -0.4869,  1.0110, -1.7588, -1.0722, -0.2249,
          -0.5102, -1.1861, -1.0295,  1.3010,  0.6817],
         [ 0.3397,  0.5344,  1.6715,  1.4443,  1.1891,  0.1882, -1.1443,
          -0.7956, -1.